/*
 * Copyright 2019, Huahuidata, Inc.
 * DataSphere is licensed under the Mulan PSL v1.
 * You can use this software according to the terms and conditions of the Mulan PSL v1.
 * You may obtain a copy of Mulan PSL v1 at:
 * http://license.coscl.org.cn/MulanPSL
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
 * PURPOSE.
 * See the Mulan PSL v1 for more details.
 */

package com.datasphere.engine.shaker.processor.prep.model;

//import javax.persistence.Id;
//import javax.persistence.Table;
import java.util.Date;

//@Table(name = "T_COLUMNS")
public class Column {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COLUMNS.ID
     *
     * @mbg.generated
     */
//    @Id
//    @javax.persistence.Column(name = "ID")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COLUMNS.NAME
     *
     * @mbg.generated
     */
//    @javax.persistence.Column(name = "NAME")
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COLUMNS.REAL_NAME
     *
     * @mbg.generated
     */
//    @javax.persistence.Column(name = "REAL_NAME")
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COLUMNS.TYPE
     *
     * @mbg.generated
     */
//    @javax.persistence.Column(name = "TYPE")
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COLUMNS.SOURCE_FLAG
     *
     * @mbg.generated
     */
//    @javax.persistence.Column(name = "SOURCE_FLAG")
    private String sourceFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COLUMNS.TABLE_ID
     *
     * @mbg.generated
     */
//    @javax.persistence.Column(name = "TABLE_ID")
    private String tableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COLUMNS.TABLE_ID
     *
     * @mbg.generated
     */
//    @javax.persistence.Column(name = "PROCESS_ID")
    private String processId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COLUMNS.STATUS
     *
     * @mbg.generated
     */
//    @javax.persistence.Column(name = "STATUS")
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COLUMNS.CHART_BAR
     *
     * @mbg.generated
     */
//    @javax.persistence.Column(name = "CHART_BAR")
    private String chartBar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COLUMNS.CHART_DISTRIBUTION
     *
     * @mbg.generated
     */
//    @javax.persistence.Column(name = "CHART_DISTRIBUTION")
    private String chartDistribution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COLUMNS.DATA_SUMMARY
     *
     * @mbg.generated
     */
//    @javax.persistence.Column(name = "DATA_SUMMARY")
    private String dataSummary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COLUMNS.DATA_STATISTICS
     *
     * @mbg.generated
     */
//    @javax.persistence.Column(name = "DATA_STATISTICS")
    private String dataStatistics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COLUMNS.PREVIEW_DATA
     *
     * @mbg.generated
     */
//    @javax.persistence.Column(name = "PREVIEW_DATA")
    private String previewData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COLUMNS.UPDATE_TIME
     *
     * @mbg.generated
     */
//    @javax.persistence.Column(name = "UPDATE_TIME")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COLUMNS.CREATE_TIME
     *
     * @mbg.generated
     */
//    @javax.persistence.Column(name = "CREATE_TIME")
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COLUMNS
     *
     * @mbg.generated
     */
    public Column(Integer id, String name, String realName, String type, String sourceFlag, String tableId, String processId, String status, String chartBar, String chartDistribution, String dataSummary, String dataStatistics, String previewData, Date updateTime, Date createTime) {
        this.id = id;
        this.name = name;
        this.realName = realName;
        this.type = type;
        this.sourceFlag = sourceFlag;
        this.tableId = tableId;
        this.processId = processId;
        this.status = status;
        this.chartBar = chartBar;
        this.chartDistribution = chartDistribution;
        this.dataSummary = dataSummary;
        this.dataStatistics = dataStatistics;
        this.previewData = previewData;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COLUMNS
     *
     * @mbg.generated
     */
    public Column() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COLUMNS.ID
     *
     * @return the value of T_COLUMNS.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COLUMNS.ID
     *
     * @param id the value for T_COLUMNS.ID
     *
     * @mbg.generated
     */
    public Column setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COLUMNS.NAME
     *
     * @return the value of T_COLUMNS.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COLUMNS.NAME
     *
     * @param name the value for T_COLUMNS.NAME
     *
     * @mbg.generated
     */
    public Column setName(String name) {
        this.name = name == null ? null : name.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COLUMNS.REAL_NAME
     *
     * @return the value of T_COLUMNS.REAL_NAME
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COLUMNS.REAL_NAME
     *
     * @param realName the value for T_COLUMNS.REAL_NAME
     *
     * @mbg.generated
     */
    public Column setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COLUMNS.TYPE
     *
     * @return the value of T_COLUMNS.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COLUMNS.TYPE
     *
     * @param type the value for T_COLUMNS.TYPE
     *
     * @mbg.generated
     */
    public Column setType(String type) {
        this.type = type == null ? null : type.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COLUMNS.SOURCE_FLAG
     *
     * @return the value of T_COLUMNS.SOURCE_FLAG
     *
     * @mbg.generated
     */
    public String getSourceFlag() {
        return sourceFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COLUMNS.SOURCE_FLAG
     *
     * @param sourceFlag the value for T_COLUMNS.SOURCE_FLAG
     *
     * @mbg.generated
     */
    public Column setSourceFlag(String sourceFlag) {
        this.sourceFlag = sourceFlag == null ? null : sourceFlag.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COLUMNS.TABLE_ID
     *
     * @return the value of T_COLUMNS.TABLE_ID
     *
     * @mbg.generated
     */
    public String getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COLUMNS.TABLE_ID
     *
     * @param tableId the value for T_COLUMNS.TABLE_ID
     *
     * @mbg.generated
     */
    public Column setTableId(String tableId) {
        this.tableId = tableId == null ? null : tableId.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COLUMNS.TABLE_ID
     *
     * @return the value of T_COLUMNS.PROCESS_ID
     *
     * @mbg.generated
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COLUMNS.TABLE_ID
     *
     * @param processId the value for T_COLUMNS.PROCESS_ID
     *
     * @mbg.generated
     */
    public Column setProcessId(String processId) {
        this.processId = processId == null ? null : processId.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COLUMNS.STATUS
     *
     * @return the value of T_COLUMNS.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COLUMNS.STATUS
     *
     * @param status the value for T_COLUMNS.STATUS
     *
     * @mbg.generated
     */
    public Column setStatus(String status) {
        this.status = status == null ? null : status.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COLUMNS.CHART_BAR
     *
     * @return the value of T_COLUMNS.CHART_BAR
     *
     * @mbg.generated
     */
    public String getChartBar() {
        return chartBar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COLUMNS.CHART_BAR
     *
     * @param chartBar the value for T_COLUMNS.CHART_BAR
     *
     * @mbg.generated
     */
    public Column setChartBar(String chartBar) {
        this.chartBar = chartBar == null ? null : chartBar.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COLUMNS.CHART_DISTRIBUTION
     *
     * @return the value of T_COLUMNS.CHART_DISTRIBUTION
     *
     * @mbg.generated
     */
    public String getChartDistribution() {
        return chartDistribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COLUMNS.CHART_DISTRIBUTION
     *
     * @param chartDistribution the value for T_COLUMNS.CHART_DISTRIBUTION
     *
     * @mbg.generated
     */
    public Column setChartDistribution(String chartDistribution) {
        this.chartDistribution = chartDistribution == null ? null : chartDistribution.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COLUMNS.DATA_SUMMARY
     *
     * @return the value of T_COLUMNS.DATA_SUMMARY
     *
     * @mbg.generated
     */
    public String getDataSummary() {
        return dataSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COLUMNS.DATA_SUMMARY
     *
     * @param dataSummary the value for T_COLUMNS.DATA_SUMMARY
     *
     * @mbg.generated
     */
    public Column setDataSummary(String dataSummary) {
        this.dataSummary = dataSummary == null ? null : dataSummary.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COLUMNS.DATA_STATISTICS
     *
     * @return the value of T_COLUMNS.DATA_STATISTICS
     *
     * @mbg.generated
     */
    public String getDataStatistics() {
        return dataStatistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COLUMNS.DATA_STATISTICS
     *
     * @param dataStatistics the value for T_COLUMNS.DATA_STATISTICS
     *
     * @mbg.generated
     */
    public Column setDataStatistics(String dataStatistics) {
        this.dataStatistics = dataStatistics == null ? null : dataStatistics.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COLUMNS.PREVIEW_DATA
     *
     * @return the value of T_COLUMNS.PREVIEW_DATA
     *
     * @mbg.generated
     */
    public String getPreviewData() {
        return previewData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COLUMNS.PREVIEW_DATA
     *
     * @param previewData the value for T_COLUMNS.PREVIEW_DATA
     *
     * @mbg.generated
     */
    public Column setPreviewData(String previewData) {
        this.previewData = previewData == null ? null : previewData.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COLUMNS.UPDATE_TIME
     *
     * @return the value of T_COLUMNS.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COLUMNS.UPDATE_TIME
     *
     * @param updateTime the value for T_COLUMNS.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Column setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COLUMNS.CREATE_TIME
     *
     * @return the value of T_COLUMNS.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COLUMNS.CREATE_TIME
     *
     * @param createTime the value for T_COLUMNS.CREATE_TIME
     *
     * @mbg.generated
     */
    public Column setCreateTime(Date createTime) {
        this.createTime = createTime;
        return this;
    }

    @Override public String toString() {
        return "Column{" + "id=" + id + ", name='" + name + '\'' + ", realName='" + realName + '\''
                + ", type='" + type + '\'' + ", sourceFlag='" + sourceFlag + '\'' + ", tableId='"
                + tableId + '\'' + ", processId='" + processId + '\'' + ", status='" + status + '\''
                + ", chartBar='" + chartBar + '\'' + ", chartDistribution='" + chartDistribution
                + '\'' + ", dataSummary='" + dataSummary + '\'' + ", dataStatistics='"
                + dataStatistics + '\'' + ", previewData='" + previewData + '\'' + ", updateTime="
                + updateTime + ", createTime=" + createTime + '}';
    }
}
