/*
 * Copyright 2019, Huahuidata, Inc.
 * DataSphere is licensed under the Mulan PSL v1.
 * You can use this software according to the terms and conditions of the Mulan PSL v1.
 * You may obtain a copy of Mulan PSL v1 at:
 * http://license.coscl.org.cn/MulanPSL
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
 * PURPOSE.
 * See the Mulan PSL v1 for more details.
 */

package com.datasphere.engine.shaker.processor.prep.model;

import java.util.Date;

//@Table(name = "T_DATAPROCESS")
public class DataProcess {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DATAPROCESS.ID
     *
     * @mbg.generated
     */
//    @Id
   // @Column(name = "ID")
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DATAPROCESS.USER_ID
     *
     * @mbg.generated
     */
   // @Column(name = "USER_ID")
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DATAPROCESS.PANEL_ID
     *
     * @mbg.generated
     */
   // @Column(name = "PANEL_ID")
    private String panelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DATAPROCESS.TABLE_ID
     *
     * @mbg.generated
     */

   // @Column(name = "DATA_KEY")
    private String dataKey;


   // @Column(name = "TABLE_ID")
    private String tableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DATAPROCESS.UPDATE_TIME
     *
     * @mbg.generated
     */
   // @Column(name = "UPDATE_TIME")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DATAPROCESS.CREATE_TIME
     *
     * @mbg.generated
     */
   // @Column(name = "CREATE_TIME")
    private Date createTime;


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DATAPROCESS
     *
     * @mbg.generated
     */
    public DataProcess(String userId, String panelId, String tableId) {
        this.userId = userId;
        this.panelId = panelId;
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DATAPROCESS
     *
     * @mbg.generated
     */
    public DataProcess(String id, String userId, String panelId, String dataKey, String tableId, Date updateTime, Date createTime) {
        this.id = id;
        this.userId = userId;
        this.panelId = panelId;
        this.dataKey = dataKey;
        this.tableId = tableId;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_DATAPROCESS
     *
     * @mbg.generated
     */
    public DataProcess() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DATAPROCESS.ID
     *
     * @return the value of T_DATAPROCESS.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DATAPROCESS.ID
     *
     * @param id the value for T_DATAPROCESS.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DATAPROCESS.USER_ID
     *
     * @return the value of T_DATAPROCESS.USER_ID
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DATAPROCESS.USER_ID
     *
     * @param userId the value for T_DATAPROCESS.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DATAPROCESS.PANEL_ID
     *
     * @return the value of T_DATAPROCESS.PANEL_ID
     *
     * @mbg.generated
     */
    public String getPanelId() {
        return panelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DATAPROCESS.PANEL_ID
     *
     * @param panelId the value for T_DATAPROCESS.PANEL_ID
     *
     * @mbg.generated
     */
    public void setPanelId(String panelId) {
        this.panelId = panelId == null ? null : panelId.trim();
    }

    public String getDataKey() {
        return dataKey;
    }

    public void setDataKey(String dataKey) {
        this.dataKey = dataKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DATAPROCESS.TABLE_ID
     *
     * @return the value of T_DATAPROCESS.TABLE_ID
     *
     * @mbg.generated
     */
    public String getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DATAPROCESS.TABLE_ID
     *
     * @param tableId the value for T_DATAPROCESS.TABLE_ID
     *
     * @mbg.generated
     */
    public void setTableId(String tableId) {
        this.tableId = tableId == null ? null : tableId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DATAPROCESS.UPDATE_TIME
     *
     * @return the value of T_DATAPROCESS.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DATAPROCESS.UPDATE_TIME
     *
     * @param updateTime the value for T_DATAPROCESS.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DATAPROCESS.CREATE_TIME
     *
     * @return the value of T_DATAPROCESS.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DATAPROCESS.CREATE_TIME
     *
     * @param createTime the value for T_DATAPROCESS.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}
