package com.datasphere.engine.shaker.processor.prep.model;

import java.util.Date;

//@Table(name = "T_PROGRAM_OPERATES")
public class ProgramOperate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROGRAM_OPERATES.ID
     *
     * @mbg.generated
     */
//    @Id
    //@javax.persistence.Column(name = "ID")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROGRAM_OPERATES.PROGRAM_ID
     *
     * @mbg.generated
     */
    //@javax.persistence.Column(name = "PROGRAM_ID")
    private Integer programId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROGRAM_OPERATES.OPERATE_ID
     *
     * @mbg.generated
     */
    //@javax.persistence.Column(name = "OPERATE_ID")
    private Integer operateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROGRAM_OPERATES.UPDATE_TIME
     *
     * @mbg.generated
     */
    //@javax.persistence.Column(name = "UPDATE_TIME")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROGRAM_OPERATES.CREATE_TIME
     *
     * @mbg.generated
     */
    //@javax.persistence.Column(name = "CREATE_TIME")
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROGRAM_OPERATES
     *
     * @mbg.generated
     */
    public ProgramOperate(Integer id, Integer programId, Integer operateId, Date updateTime, Date createTime) {
        this.id = id;
        this.programId = programId;
        this.operateId = operateId;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROGRAM_OPERATES
     *
     * @mbg.generated
     */
    public ProgramOperate() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROGRAM_OPERATES.ID
     *
     * @return the value of T_PROGRAM_OPERATES.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROGRAM_OPERATES.ID
     *
     * @param id the value for T_PROGRAM_OPERATES.ID
     *
     * @mbg.generated
     */
    public ProgramOperate setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROGRAM_OPERATES.PROGRAM_ID
     *
     * @return the value of T_PROGRAM_OPERATES.PROGRAM_ID
     *
     * @mbg.generated
     */
    public Integer getProgramId() {
        return programId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROGRAM_OPERATES.PROGRAM_ID
     *
     * @param programId the value for T_PROGRAM_OPERATES.PROGRAM_ID
     *
     * @mbg.generated
     */
    public ProgramOperate setProgramId(Integer programId) {
        this.programId = programId;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROGRAM_OPERATES.OPERATE_ID
     *
     * @return the value of T_PROGRAM_OPERATES.OPERATE_ID
     *
     * @mbg.generated
     */
    public Integer getOperateId() {
        return operateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROGRAM_OPERATES.OPERATE_ID
     *
     * @param operateId the value for T_PROGRAM_OPERATES.OPERATE_ID
     *
     * @mbg.generated
     */
    public ProgramOperate setOperateId(Integer operateId) {
        this.operateId = operateId;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROGRAM_OPERATES.UPDATE_TIME
     *
     * @return the value of T_PROGRAM_OPERATES.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROGRAM_OPERATES.UPDATE_TIME
     *
     * @param updateTime the value for T_PROGRAM_OPERATES.UPDATE_TIME
     *
     * @mbg.generated
     */
    public ProgramOperate setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROGRAM_OPERATES.CREATE_TIME
     *
     * @return the value of T_PROGRAM_OPERATES.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROGRAM_OPERATES.CREATE_TIME
     *
     * @param createTime the value for T_PROGRAM_OPERATES.CREATE_TIME
     *
     * @mbg.generated
     */
    public ProgramOperate setCreateTime(Date createTime) {
        this.createTime = createTime;
        return this;
    }
}