package com.datasphere.engine.shaker.processor.prep.model;

//import javax.persistence.Id;
//import javax.persistence.Table;
import java.util.Date;

//@Table(name = "T_PROGRAM_COLUMNS")
public class ProgramColumn {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROGRAM_COLUMNS.ID
     *
     * @mbg.generated
     */
//    @Id
    //@javax.persistence.Column(name = "ID")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROGRAM_COLUMNS.PROGRAM_ID
     *
     * @mbg.generated
     */
    //@javax.persistence.Column(name = "PROGRAM_ID")
    private Integer programId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROGRAM_COLUMNS.COLUMN_ID
     *
     * @mbg.generated
     */
    //@javax.persistence.Column(name = "COLUMN_ID")
    private Integer columnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROGRAM_COLUMNS.COLUMN_ORDER
     *
     * @mbg.generated
     */
    //@javax.persistence.Column(name = "COLUMN_ORDER")
    private Integer columnOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROGRAM_COLUMNS.UPDATE_TIME
     *
     * @mbg.generated
     */
    //@javax.persistence.Column(name = "UPDATE_TIME")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROGRAM_COLUMNS.CREATE_TIME
     *
     * @mbg.generated
     */
    //@javax.persistence.Column(name = "CREATE_TIME")
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROGRAM_COLUMNS
     *
     * @mbg.generated
     */
    public ProgramColumn(Integer id, Integer programId, Integer columnId, Integer columnOrder, Date updateTime, Date createTime) {
        this.id = id;
        this.programId = programId;
        this.columnId = columnId;
        this.columnOrder = columnOrder;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    public ProgramColumn(Integer programId, Integer columnId, Integer columnOrder, Date updateTime, Date createTime) {
        this.programId = programId;
        this.columnId = columnId;
        this.columnOrder = columnOrder;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROGRAM_COLUMNS
     *
     * @mbg.generated
     */
    public ProgramColumn() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROGRAM_COLUMNS.ID
     *
     * @return the value of T_PROGRAM_COLUMNS.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROGRAM_COLUMNS.ID
     *
     * @param id the value for T_PROGRAM_COLUMNS.ID
     *
     * @mbg.generated
     */
    public ProgramColumn setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROGRAM_COLUMNS.PROGRAM_ID
     *
     * @return the value of T_PROGRAM_COLUMNS.PROGRAM_ID
     *
     * @mbg.generated
     */
    public Integer getProgramId() {
        return programId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROGRAM_COLUMNS.PROGRAM_ID
     *
     * @param programId the value for T_PROGRAM_COLUMNS.PROGRAM_ID
     *
     * @mbg.generated
     */
    public ProgramColumn setProgramId(Integer programId) {
        this.programId = programId;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROGRAM_COLUMNS.COLUMN_ID
     *
     * @return the value of T_PROGRAM_COLUMNS.COLUMN_ID
     *
     * @mbg.generated
     */
    public Integer getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROGRAM_COLUMNS.COLUMN_ID
     *
     * @param columnId the value for T_PROGRAM_COLUMNS.COLUMN_ID
     *
     * @mbg.generated
     */
    public ProgramColumn setColumnId(Integer columnId) {
        this.columnId = columnId;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROGRAM_COLUMNS.COLUMN_ORDER
     *
     * @return the value of T_PROGRAM_COLUMNS.COLUMN_ORDER
     *
     * @mbg.generated
     */
    public Integer getColumnOrder() {
        return columnOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROGRAM_COLUMNS.COLUMN_ORDER
     *
     * @param columnOrder the value for T_PROGRAM_COLUMNS.COLUMN_ORDER
     *
     * @mbg.generated
     */
    public ProgramColumn setColumnOrder(Integer columnOrder) {
        this.columnOrder = columnOrder;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROGRAM_COLUMNS.UPDATE_TIME
     *
     * @return the value of T_PROGRAM_COLUMNS.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROGRAM_COLUMNS.UPDATE_TIME
     *
     * @param updateTime the value for T_PROGRAM_COLUMNS.UPDATE_TIME
     *
     * @mbg.generated
     */
    public ProgramColumn setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROGRAM_COLUMNS.CREATE_TIME
     *
     * @return the value of T_PROGRAM_COLUMNS.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROGRAM_COLUMNS.CREATE_TIME
     *
     * @param createTime the value for T_PROGRAM_COLUMNS.CREATE_TIME
     *
     * @mbg.generated
     */
    public ProgramColumn setCreateTime(Date createTime) {
        this.createTime = createTime;
        return this;
    }
}